In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%ls drive/MyDrive/MovieLensRecommendationEngine/data
%cd drive/MyDrive/MovieLensRecommendationEngine/data

links.csv  movies.csv  ratings.csv  README.txt  tags.csv
/content/drive/.shortcut-targets-by-id/19vImGpRsJLADjA6hk42eW6GVrt1ewBYU/MovieLensRecommendationEngine/data

In [ ]:
import pandas as pd
import numpy as np
from itertools import combinations

In [ ]:
#df_genome_scores = pd.read_csv("/content/drive/MyDrive/MovieLensRecommendationEngine/data/genome-scores.csv")
#df_genome_tags = pd.read_csv("/content/drive/MyDrive/MovieLensRecommendationEngine/data/genome-tags.csv")
df_links = pd.read_csv("/content/drive/MyDrive/MovieLensRecommendationEngine/data/links.csv")
df_movies = pd.read_csv("/content/drive/MyDrive/MovieLensRecommendationEngine/data/movies.csv")
df_ratings = pd.read_csv("/content/drive/MyDrive/MovieLensRecommendationEngine/data/ratings.csv")
df_tags = pd.read_csv("/content/drive/MyDrive/MovieLensRecommendationEngine/data/tags.csv")

In [ ]:
df_movies.head(5)

   movieId  ...                                       genres
0        1  ...  Adventure|Animation|Children|Comedy|Fantasy
1        2  ...                   Adventure|Children|Fantasy
2        3  ...                               Comedy|Romance
3        4  ...                         Comedy|Drama|Romance
4        5  ...                                       Comedy

[5 rows x 3 columns]

In [ ]:
high_ratings=df_ratings[ (df_ratings['userId']==41) & (df_ratings['rating']==5.0)]
high_r=list(high_ratings['movieId'])
print(high_r)
list(df_movies[df_movies['movieId'].isin(high_r)]['genres'])

[296, 1206, 1258, 1259, 1721, 2160, 2712, 3948, 4022, 4816, 4848, 4878, 6287, 6763, 6874, 7173, 7293, 7438, 55820, 87869, 104879, 116897]

['Comedy|Crime|Drama|Thriller',
 'Crime|Drama|Sci-Fi|Thriller',
 'Horror',
 'Adventure|Drama',
 'Drama|Romance',
 'Drama|Horror|Thriller',
 'Drama|Mystery|Thriller',
 'Comedy',
 'Drama',
 'Comedy',
 'Crime|Drama|Film-Noir|Mystery|Thriller',
 'Drama|Mystery|Sci-Fi|Thriller',
 'Comedy',
 'Comedy|Crime',
 'Action|Crime|Thriller',
 'Comedy|Romance',
 'Comedy|Romance',
 'Action|Drama|Thriller',
 'Crime|Drama',
 'Comedy|Crime',
 'Drama|Mystery|Thriller',
 'Comedy|Drama|Thriller']

In [ ]:
#df_movies.head()
len(df_tags['tag'].unique())

1589

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
#can change upper limit of range to increase number of genres /increase dimensions of the vector(no of genres considered as a column) considered
tf = TfidfVectorizer(analyzer=lambda s: (c for i in range(1,4)
                                             for c in combinations(s.split('|'), r=i)))
tfidf_matrix = tf.fit_transform(df_movies['genres'])
#tfidf_matrix.shape
pd.DataFrame(tfidf_matrix.todense(), columns=tf.get_feature_names(), index=df_movies.title).sample(5, axis=1).sample(10, axis=0)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

                                                    (Animation, Drama, Musical)  ...  (Crime, Drama, Thriller)
title                                                                            ...
Harry Potter and the Sorcerer's Stone (a.k.a. H...                          0.0  ...                  0.000000
Beasts of No Nation (2015)                                                  0.0  ...                  0.000000
What Happened Was... (1994)                                                 0.0  ...                  0.000000
Caddyshack II (1988)                                                        0.0  ...                  0.000000
Night and Fog (Nuit et brouillard) (1955)                                   0.0  ...                  0.000000
Rudderless (2014)                                                           0.0  ...                  0.000000
Unknown (2006)                                                              0.0  ...                  0.000000
Taken (2008)                                                                0.0  ...                  0.310516
Make Way for Tomorrow (1937)                                                0.0  ...                  0.000000
Basquiat (1996)                                                             0.0  ...                  0.000000

[10 rows x 5 columns]

In [ ]:
#pd.DataFrame(tfidf_matrix.todense(), columns=tf.get_feature_names(), index=df_movies.title).sample(10, axis=1).sample(10, axis=0)
vectors=pd.DataFrame(tfidf_matrix.todense(), columns=tf.get_feature_names(), index=df_movies.title)
print(vectors)
#print(vectors.mean(axis=0))

                                           ((no genres listed),)  ...  (Western, IMAX)
title                                                             ...
Toy Story (1995)                                             0.0  ...              0.0
Jumanji (1995)                                               0.0  ...              0.0
Grumpier Old Men (1995)                                      0.0  ...              0.0
Waiting to Exhale (1995)                                     0.0  ...              0.0
Father of the Bride Part II (1995)                           0.0  ...              0.0
...                                                          ...  ...              ...
Black Butler: Book of the Atlantic (2017)                    0.0  ...              0.0
No Game No Life: Zero (2017)                                 0.0  ...              0.0
Flint (2017)                                                 0.0  ...              0.0
Bungo Stray Dogs: Dead Apple (2018)                          0.0  ...              0.0
Andrew Dice Clay: Dice Rules (1991)                          0.0  ...              0.0

[9742 rows x 783 columns]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
pd.DataFrame(tfidf_matrix.todense(), columns=tf.get_feature_names(), index=df_movies.title).sample(20, axis=1).sample(10, axis=0)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

                                                    (Fantasy, Musical, IMAX)  ...  (Film-Noir, Sci-Fi, Thriller)
title                                                                         ...
Speechless (1994)                                                        0.0  ...                            0.0
Whistleblower, The (2010)                                                0.0  ...                            0.0
Villain (1971)                                                           0.0  ...                            0.0
Man Escaped, A (Un  condamné à mort s'est échap...                       0.0  ...                            0.0
Facing Windows (Finestra di fronte, La) (2003)                           0.0  ...                            0.0
Leprechaun 3 (1995)                                                      0.0  ...                            0.0
Hustler, The (1961)                                                      0.0  ...                            0.0
Camino (2016)                                                            0.0  ...                            0.0
Love Potion #9 (1992)                                                    0.0  ...                            0.0
Four Days in September (O Que É Isso, Companhei...                       0.0  ...                            0.0

[10 rows x 20 columns]

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix)

In [ ]:
cosine_sim_df = pd.DataFrame(cosine_sim, index=df_movies['title'], columns=df_movies['title'])
print('Shape:', cosine_sim_df.shape)
cosine_sim_df.sample(5, axis=1).round(2)

Shape: (9742, 9742)

title                                      Son in Law (1993)  ...  Magnolia (1999)
title                                                         ...
Toy Story (1995)                                        0.02  ...             0.00
Jumanji (1995)                                          0.00  ...             0.00
Grumpier Old Men (1995)                                 0.59  ...             0.00
Waiting to Exhale (1995)                                1.00  ...             0.22
Father of the Bride Part II (1995)                      0.24  ...             0.00
...                                                      ...  ...              ...
Black Butler: Book of the Atlantic (2017)               0.03  ...             0.00
No Game No Life: Zero (2017)                            0.04  ...             0.00
Flint (2017)                                            0.22  ...             1.00
Bungo Stray Dogs: Dead Apple (2018)                     0.00  ...             0.00
Andrew Dice Clay: Dice Rules (1991)                     0.24  ...             0.00

[9742 rows x 5 columns]

In [ ]:
def genre_recommendations(i, M, items, k=10):
    """
    Recommends movies based on a similarity dataframe

    Parameters
    ----------
    i : str
        Movie (index of the similarity dataframe)
    M : pd.DataFrame
        Similarity dataframe, symmetric, with movies as indices and columns
    items : pd.DataFrame
        Contains both the title and some other features used to define similarity
    k : int
        Amount of recommendations to return

    """
    
    ix = M.loc[:,i].to_numpy().argpartition(range(-1,-k,-1))
    print("ix",ix,ix.shape)
    #print('z',z)
    closest = M.columns[ix[-1:-(k+2):-1]]
    closest = closest.drop(i, errors='ignore')
    return pd.DataFrame(closest).merge(items).head(k)

In [ ]:
def genre_recommendations1(user, M, items, k=10):
    """
    Recommends movies based on a similarity dataframe

    Parameters
    ----------
    i : str
        Movie (index of the similarity dataframe)
    M : pd.DataFrame
        Similarity dataframe, symmetric, with movies as indices and columns
    items : pd.DataFrame
        Contains both the title and some other features used to define similarity
    k : int
        Amount of recommendations to return

    """
    high_ratings=df_ratings[ (df_ratings['userId']==user) & (df_ratings['rating']==5.0)]
    high_r=list(high_ratings['movieId'])
    #print(high_r)
    i=list(df_movies[df_movies['movieId'].isin(high_r)]['title'])
    print('i',i)
    ix = M.loc[:,i[0]]#.to_numpy().argpartition(range(-1,-k,-1))
    
    for x in range(1,len(i)):
      ix+=M.loc[:,i[x]].to_numpy().argpartition(range(-1,-k,-1))
      #ix+=a
      #print(a,a.shape,ix.shape)
    ix=ix.sort_values(ascending=False)
    #print("ix",ix.shape,'\n',ix.iloc[:20])
    #print('z',z)
    z= ix.head(10).index.values
    print(df_movies[df_movies['title'].isin(z)])
    return df_movies[df_movies['title'].isin(z)]
    #ix=ix.to_numpy().argpartition(range(-1,-k,-1))
    #closest = M.columns[ix[-1:-(k+2):-1]]
    #closest = closest.drop(i, errors='ignore')
    #return pd.DataFrame(closest).merge(items).head(k)

In [ ]:
df_movies[df_movies['title'].str.startswith('Pulp')]

     movieId                title                       genres
257      296  Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller

In [ ]:
#genre_recommendations('2001: A Space Odyssey (1968)', cosine_sim_df, df_movies[['title', 'genres']])
genre_recommendations1(18, cosine_sim_df, df_movies[['title', 'genres']])
#genre_recommendations1(['Inglourious Basterds (2009)','Pulp Fiction (1994)'], cosine_sim_df, df_movies[['title', 'genres']])
#genre_recommendations1(['Chronicles of Narnia: Prince Caspian, The (2008)','Hobbit: The Desolation of Smaug, The (2013)'], cosine_sim_df, df_movies[['title', 'genres']])

i ['Usual Suspects, The (1995)', 'Shawshank Redemption, The (1994)', 'Citizen Kane (1941)', 'Good, the Bad and the Ugly, The (Buono, il brutto, il cattivo, Il) (1966)', '12 Angry Men (1957)', "Once Upon a Time in the West (C'era una volta il West) (1968)", 'Godfather: Part II, The (1974)']
    movieId                               title                     genres
2         3             Grumpier Old Men (1995)             Comedy|Romance
3         4            Waiting to Exhale (1995)       Comedy|Drama|Romance
4         5  Father of the Bride Part II (1995)                     Comedy
5         6                         Heat (1995)      Action|Crime|Thriller
6         7                      Sabrina (1995)             Comedy|Romance
7         8                 Tom and Huck (1995)         Adventure|Children
8         9                 Sudden Death (1995)                     Action
9        10                    GoldenEye (1995)  Action|Adventure|Thriller
10       11      American President, The (1995)       Comedy|Drama|Romance
11       12  Dracula: Dead and Loving It (1995)              Comedy|Horror

    movieId                               title                     genres
2         3             Grumpier Old Men (1995)             Comedy|Romance
3         4            Waiting to Exhale (1995)       Comedy|Drama|Romance
4         5  Father of the Bride Part II (1995)                     Comedy
5         6                         Heat (1995)      Action|Crime|Thriller
6         7                      Sabrina (1995)             Comedy|Romance
7         8                 Tom and Huck (1995)         Adventure|Children
8         9                 Sudden Death (1995)                     Action
9        10                    GoldenEye (1995)  Action|Adventure|Thriller
10       11      American President, The (1995)       Comedy|Drama|Romance
11       12  Dracula: Dead and Loving It (1995)              Comedy|Horror